common: &common
  adapter: postgresql
  host: localhost
  username: rails
  password: rails

development:
  <<: *common
  database: sample_app

test:
  <<: *common
  database: sample_app

production:
  <<: *common
  database: sample_app